In [ ]:
# Standard workhorses
import numpy as np
import matplotlib.pyplot as plt
#from sympy import sympify
from fractions import Fraction

# Seaborn, useful for graphics
import seaborn as sns

# Magic function to make matplotlib inline; other style specs must come AFTER
%matplotlib inline

# This enables SVG graphics inline (only use with static plots (non-Bokeh))
%config InlineBackend.figure_formats = {'svg',}

# **Desarrollo de un esquema de diferencias finitas**

Como ejemplo simple de la formulación de un esquema de diferencias finitas, veamos como se podría llevara a cabo la formulación de un esquema de orden 4 para una segunda derivada.

En una formulación centrada se necesitaran tantos puntos de expansión hacia adelante, como hacia atrás.  Adicionalmente, dado que queremos un esquema de orden 4 para segunda derivada, es claro que necesitaremos incluir de manera explícita los términos hasta, al menos, la sexta derivada ($f^{(6)}$).

Bajo las anteriores consideraciones, se proponen usar las siguientes expansiones:

\begin{align}
f_{i-3} &= f_{i} - 3 \Delta x f^{(1)} + \dfrac{9\Delta x^2}{2!} f^{(2)} -
 \dfrac{27\Delta x^3}{3!} f^{(3)} + \dfrac{81\Delta x^4}{4!} f^{(4)} - \dfrac{243\Delta x^5}{5!} f^{(5)} + \dfrac{729\Delta x^6}{6!} f^{(6)}  \\
 \\
f_{i-2} &= f_{i} - 2 \Delta x f^{(1)} + \dfrac{4\Delta x^2}{2!} f^{(2)} -
 \dfrac{8\Delta x^3}{3!} f^{(3)} + \dfrac{16\Delta x^4}{4!} f^{(4)} - \dfrac{32\Delta x^5}{5!} f^{(5)} + \dfrac{64\Delta x^6}{6!} f^{(6)}  \\
 \\
f_{i-1} &= f_{i} - \Delta x f^{(1)} + \dfrac{\Delta x^2}{2!} f^{(2)} -
 \dfrac{\Delta x^3}{3!} f^{(3)} + \dfrac{\Delta x^4}{4!} f^{(4)} - \dfrac{\Delta x^5}{5!} f^{(5)} + \dfrac{\Delta x^6}{6!} f^{(6)}  \\
 \\
 f_{i+1} &= f_{i} + \Delta x f^{(1)} + \dfrac{\Delta x^2}{2!} f^{(2)} +
 \dfrac{\Delta x^3}{3!} f^{(3)} + \dfrac{\Delta x^4}{4!} f^{(4)} + \dfrac{\Delta x^5}{5!} f^{(5)} + \dfrac{\Delta x^6}{6!} f^{(6)}  \\
\\
 f_{i+2} &= f_{i} + 2 \Delta x f^{(1)} + \dfrac{4\Delta x^2}{2!} f^{(2)} +
 \dfrac{8\Delta x^3}{3!} f^{(3)} + \dfrac{16\Delta x^4}{4!} f^{(4)} + \dfrac{32\Delta x^5}{5!} f^{(5)} + \dfrac{64\Delta x^6}{6!} f^{(6)}  \\
 \\
 f_{i+3} &= f_{i} + 3 \Delta x f^{(1)} + \dfrac{9\Delta x^2}{2!} f^{(2)} +
 \dfrac{27\Delta x^3}{3!} f^{(3)} + \dfrac{81\Delta x^4}{4!} f^{(4)} + \dfrac{243\Delta x^5}{5!} f^{(5)} + \dfrac{729\Delta x^6}{6!} f^{(6)}
\end{align}

La combinación lineal de este conjunto de ecuaciones, puede escribirse como

\begin{align}
\omega_0\,f_{i-3} &= \omega_{0}\left(f_{i} - 3 \Delta x f^{(1)} + \dfrac{9\Delta x^2}{2!} f^{(2)} -
 \dfrac{27\Delta x^3}{3!} f^{(3)} + \dfrac{81\Delta x^4}{4!} f^{(4)} - \dfrac{243\Delta x^5}{5!} f^{(5)} + \dfrac{729\Delta x^6}{6!} f^{(6)}\right)  \\
 \\
\omega_1\,f_{i-2} &= \omega_{1}\left(f_{i} - 2 \Delta x f^{(1)} + \dfrac{4\Delta x^2}{2!} f^{(2)} -
 \dfrac{8\Delta x^3}{3!} f^{(3)} + \dfrac{16\Delta x^4}{4!} f^{(4)} - \dfrac{32\Delta x^5}{5!} f^{(5)} + \dfrac{64\Delta x^6}{6!} f^{(6)}\right)  \\
 \\
\omega_2\,f_{i-1} &= \omega_{2}\left(f_{i} - \Delta x f^{(1)} + \dfrac{\Delta x^2}{2!} f^{(2)} -
 \dfrac{\Delta x^3}{3!} f^{(3)} + \dfrac{\Delta x^4}{4!} f^{(4)} - \dfrac{\Delta x^5}{5!} f^{(5)} + \dfrac{\Delta x^6}{6!} f^{(6)}\right)  \\
 \\
\omega_3\,f_{i+1} &= \omega_{3}\left(f_{i} + \Delta x f^{(1)} + \dfrac{\Delta x^2}{2!} f^{(2)} +
 \dfrac{\Delta x^3}{3!} f^{(3)} + \dfrac{\Delta x^4}{4!} f^{(4)} + \dfrac{\Delta x^5}{5!} f^{(5)} + \dfrac{\Delta x^6}{6!} f^{(6)}\right)  \\
 \\
\omega_4\,f_{i+2} &= \omega_{4}\left(f_{i} + 2 \Delta x f^{(1)} + \dfrac{4\Delta x^2}{2!} f^{(2)} +
 \dfrac{8\Delta x^3}{3!} f^{(3)} + \dfrac{16\Delta x^4}{4!} f^{(4)} + \dfrac{32\Delta x^5}{5!} f^{(5)} + \dfrac{64\Delta x^6}{6!} f^{(6)}\right)  \\
 \\
\omega_5\,f_{i+3} &= \omega_{5}\left(f_{i} + 3 \Delta x f^{(1)} + \dfrac{9\Delta x^2}{2!} f^{(2)} +
 \dfrac{27\Delta x^3}{3!} f^{(3)} + \dfrac{81\Delta x^4}{4!} f^{(4)} + \dfrac{243\Delta x^5}{5!} f^{(5)} + \dfrac{729\Delta x^6}{6!} f^{(6)} \right)
\end{align}

Para la formulación del esquema propuesto, forzaremos solamente seis condiciones:

* Coeficientes asociados a: $\Delta x f^{(1)}$, $\Delta x^3 f^{(3)}/3!$, $\Delta x^4 f^{(4)}/4!$, y $\Delta x^5 f^{(5)}/5!$,  todos deben ser simultaneamente $0$.
* Coeficiente asociado a: $\frac{\Delta x^2 f^{(2)}}{2!}$ debe ser exactamente $1$.
* Coeficiente asociado a: $\frac{\Delta x^6 f^{(6)}}{6!}$ va a ser un valor de holgura $\alpha$.

De esta manera, el sistema de ecuaciones a resolver para encontrar el esquema buscado, se puede expresar como

\begin{equation}
\begin{bmatrix}
-3 & -2 & -1 & 1 & 2 & 3 \\
9 & 4 & 1 & 1 & 4 & 9 \\
-27 & -8 & -1 & 1 & 8 & 27 \\
81 & 16 & 1 & 1 & 16 & 81 \\
-243 & -32 & -1 & 1 & 32 & 243 \\
729 & 64 & 1 & 1 & 64 & 729
\end{bmatrix}
\begin{bmatrix}
\omega_0 \\
\omega_1 \\
\omega_2 \\
\omega_3 \\
\omega_4 \\
\omega_5
\end{bmatrix}
=
\begin{bmatrix}
0 \\
2! \\
0 \\
0 \\
0 \\
\alpha
\end{bmatrix}
\end{equation}

Sistema que podemos resolver de manera simple con un código numérico como el mostrado a continuación

In [ ]:
matCoefs = np.array([[-3.0,-2.0,-1.0,1.0,2.0,3.0],
                     [ 9.0, 4.0, 1.0,1.0,4.0,9.0],
                     [-27.0,-8.0,-1.0,1.0,8.0,27.0],
                     [ 81.0,16.0, 1.0,1.0,16.0,81.0],
                     [-243.0,-32.0,-1.0,1.0,32.0,243.0],
                     [729.0,64.0, 1.0,1.0,64.0,729.0]
                     ],dtype=np.float64);
alpha = 0.0;
vecRHS = np.array([0.0,2.0,0.0,0.0,0.0,alpha],dtype=np.float64);

vecOmegas = np.linalg.solve(matCoefs,vecRHS)

vecOmegas

array([ 0.01111111, -0.15      ,  1.5       ,  1.5       , -0.15      ,
        0.01111111])

In [ ]:
  1.0/vecOmegas[0]

90.00000000000003

In [ ]:
360.0*vecOmegas[1]

-53.999999999999986

In [ ]:
360*vecOmegas[2]

539.9999999999999

In [ ]:
360*vecOmegas[3]

539.9999999999999

In [ ]:
360*vecOmegas[4]

-53.99999999999998

In [ ]:
360*vecOmegas[5]

3.999999999999998

De esta manera podemos ver que, bajo este enfoque, el esquema de diferencias finitas de orden 5 (con $\alpha=0$) para segunda derivada se puede plantear como

\begin{equation}
\dfrac{\partial^2 f}{\partial x^2} = \dfrac{4f_{i-3}-54f_{i-2}+540f_{i-1}-
980f_{i}+540f_{i+1}-54f_{i+2}+4f_{i+3}}{360 \Delta x^2} + O(\Delta x^5)
\end{equation}

In [ ]:
matCoefs = np.array([[1.0,1.0, 1.0,1.0],
                     [1.0, 0.0, 0.0,-1.0],
                     [-1.0/3.0,-1.0/12.0,-1.0/12.0,-1.0/3.0],
                     [2.0/15.0, 1.0/60.0, -1.0/60.0, -2.0/15.0]
                     ],dtype=np.float64);
alpha = 1.0;
vecRHS = np.array([alpha,0.0,0.0,0.0],dtype=np.float64);

vecOmegas = np.linalg.solve(matCoefs,vecRHS)

vecOmegas

array([-0.16666667,  0.66666667,  0.66666667, -0.16666667])

In [ ]:
6.0*vecOmegas[0]

-1.0000000000000004

In [ ]:
6.0*vecOmegas[1]

4.0

In [ ]:
vecOmegas.sum()*6.0

5.999999999999999

In [ ]:
6.0*vecOmegas[2]

4.0

In [ ]:
6.0*vecOmegas[3]

-0.9999999999999998

In [ ]:
EsquemaVec=np.array([6.0*vecOmegas[0],24.0*vecOmegas[1],24.0*vecOmegas[2],6.0*vecOmegas[3]])

In [ ]:
EsquemaVec

array([-1., 16., 16., -1.])